# Generated by Django 3.2.5 on 2021-07-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210723_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.CharField(max_length=20, null=True)),
                ('is_superuser', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('is_staff', models.BooleanField()),
                ('data_joined', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
