# Generated by Django 3.2.5 on 2021-07-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_data_joined_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.BigIntegerField(null=True),
        ),
    ]
