# Generated by Django 3.2.5 on 2021-08-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20210801_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='start',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_joined',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
