# Generated by Django 3.2.5 on 2021-08-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HisOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(max_length=255)),
                ('conf', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phonenumber', models.CharField(max_length=30, null=True)),
                ('peo', models.CharField(max_length=50, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('time_joined', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='PayedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(max_length=255)),
                ('conf', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phonenumber', models.CharField(max_length=30, null=True)),
                ('peo', models.CharField(max_length=50, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('time_joined', models.CharField(max_length=50, null=True)),
                ('start', models.BooleanField(default='0')),
                ('price', models.IntegerField(default='0')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='start',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_joined',
        ),
    ]
