# Generated by Django 3.2.5 on 2021-07-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
