# Generated by Django 3.2.5 on 2021-07-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210729_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classify',
            old_name='product',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='lanmu',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
