# Generated by Django 3.2.5 on 2021-07-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210729_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classify',
            old_name='price',
            new_name='oth',
        ),
        migrations.RemoveField(
            model_name='classify',
            name='name',
        ),
        migrations.AddField(
            model_name='classify',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
